export const instruments = [
    "Piano",
    "Guitarra",
    "Guitarra Eléctrica",
    "Violín",
    "Bajo",
    "Batería",
    "Saxofón",
    "Trompeta",
    "Flauta",
    "Clarinete",
    "Trombón",
    "Arpa",
    "Chelo",
    "Acordeón",
    "Mandolina",
    "Tuba",
    "Contrabajo",
    "Xilófono",
    "Gaita",
    "Corneta",
    "Cello",
    "Melódica",
    "Bongo",
    "Ukelele",
    "Percusión",
  ];