export const sports = [
    "Fútbol",
    "Básquet",
    "Tenis",
    "Natación",
    "Atletismo",
    "Ciclismo",
    "Golf",
    "Rugby",
    "Hockey",
    "Hockey Sobre Hielo",
    "Voleibol",
    "Boxeo",
    "Artes Marciales",
    "Esquí",
    "Patinaje",
    "Béisbol",
    "Remo",
    "Judo",
    "Karate",
    "Taekwondo",
    "Esgrima",
    "Ajedrez",
    "Surf",
    "Tiro con Arco",
    "Esquí Acuático",
    "Handbol",
    "Lucha Libre",
    "Automovilismo",
    "Motociclismo",
    "Paracaidismo",
    "Snowboard",
    "Buceo",
    "Montañismo",
  ];