name: Build and Publish Image To DuckerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        docker build . -t ramoro/convocarte-frontend-docker-hub:latest \
          --build-arg VUE_APP_BACKEND_API_URL=https://deploy-convocarte-backend-prod.onrender.com/ \
          --build-arg VUE_APP_FRONTEND_API_URL=https://convocarte-frontend.onrender.com/
    - name: Publish
      run: |
       docker login -u ramoro -p ${{ secrets.DOCKERHUB_TOKEN }}
       docker push ramoro/convocarte-frontend-docker-hub:latest
    - name: Deploy
      # Only run this step if the branch is main
      if: github.ref == 'refs/heads/main'
      env:
        deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: |
        curl "$deploy_url"